server:
  port: 10010
spring:
  application:
    name: yigou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
zuul:
  prefix: /api
  routes:
    item.service: /item/**   #路由到商品的微服务
    search-service: /search/**  #搜索微服务
    user-service: /user/**   #用户微服务
    auth-service: /auth/**   # 授权中心微服务
  add-host-header: true  #携带请求本身的head头信息
  sensitive-headers:  #覆盖默认敏感头信息
yigou:
  jwt:
    pubKeyPath: C:\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: YG_TOKEN
  filter:
    allowPaths:
      - /api/auth    //以-开头的路径代表集合
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item